name: Build & Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm ci
    - run: npm run build -- --production
    - run: npm run build-service -- --env production
    - run: npm run package
    - run: echo RELEASE_FILENAME_IPK=`ls *.ipk` >> $GITHUB_ENV
    - run: npm run manifest

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload IPK asset
      id: upload-ipk-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/${{env.RELEASE_FILENAME_IPK}}
        asset_name: ${{env.RELEASE_FILENAME_IPK}}
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload Manifest asset
      id: upload-manifest-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/org.webosbrew.hbchannel.manifest.json
        asset_name: org.webosbrew.hbchannel.manifest.json
        asset_content_type: application/json
